project_name: 'F-MAE'
dataset: 'fits'
seed: 42

trainer:
  accelerator: 'gpu' # set to 1 to disable multi gpu training
  devices: 1
  num_nodes: 1
  strategy: 'auto' # set to null to disable multi gpu training
  fast_dev_run: False # debugging mode
  precision: bf16 # [16, 32, 'bf16'], often overriden
  deterministic: True

dataloading:
  num_workers: 8  # often overriden
  prefetch_factor: 30
  persistent_workers: False  # torch default is False
  pin_memory: True
