preset: 'none'

model:
    n_epochs: 600
    warmup_epochs: 10  # Scheduler linear warmup
    masking_ratio: 0.75
    lr: 0.0003 
    momentum: 0.9
    weight_decay: 0.0005
    beta_1: 0.9
    beta_2: 0.95

architecture:
    encoder:
        preset: 'vit_small'
        patch_size: 8
        embed_dim: 768
        depth: 12
        num_heads: 12
        mlp_ratio: 4
  
    decoder: 
        preset: 'small'
        embed_dim: 512
        depth: 8
        num_heads: 16
data:
    img_size: 96
    in_chans: 3
    classes: 10
    test_size: 0.3 
    batch_size: 1024

linear:
    n_epochs: 50
    opt: 'adam'
    lr: 0.0003
    batch_size: 300
    momentum: 0
    nesterov: False
    weight_decay: 0.5
